### ISSUE TITLE
About gender of SMPL-X

### ISSUE THREAD

**Issue by uyoung-jeong** [paulchhuang/rich_toolkit#5]
hello. Firstly, thank you for providing the dataset.
However, I have a question about the gender of the SMPL-X ground-truth provided by the dataset.
It seems that both the paper and the dataset do not mention the gender information for each subject.
So is the SMPL-X annotation you provide based on a gender neutral model?
I ask because I need clarification on this aspect.

**Comment by paulchhuang** [comment]
Hi, the ground truths are based on each subject's own gender. For example, if subject no. 1 is male, then you need to load male SMPL-X model so that the ground truth SMPL-X params would return a correct pose and shape. 
Gender information is stored inside `resource/gender.json`. Take a look at this line https://github.com/paulchhuang/rich_toolkit/blob/main/smplx2images.py#L16, to see how we map from subject id to the corresponding gender.
