### ISSUE TITLE
About train/test dataset partition

### ISSUE THREAD

**Issue by rabbitchenrui** [paulchhuang/rich_toolkit#8]
Hi, I find that, scene in training data and test data is various greatly. like this table
![1731928113454](https://github.com/user-attachments/assets/b9bd14a3-c34a-449e-914c-f6d2745f690e)
Do you remember how you do the dataset partition? Or Can I changge the dataset partition? because I want to train a scene model to utilize scene information to help human pose estimation... But different scene in training dataset and test dataset makes is hard to leaening any info meaningful....

**Comment by rabbitchenrui** [comment]
@paulchhuang looking forward to your reply

**Comment by paulchhuang** [comment]
Hi @rabbitchenrui, 
"Gym" is completely withheld from training. This is to assess models' ability to generalize to unseen scenes. There are LectureHall & ParkingLot2 which have overlaps between train and test sets; one can first make sure the algorithm works on them and then try the more challenging Gym.

It is not suggested to change the dataset's partition, because it would make the comparison chaotic. However, we understand one partition cannot serve all purposes. If you'd like to define your partition, please describe it in the paper and share it on the project website/repo so that people can fully reproduce it.
